// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type User struct {
	ID              int64       `json:"id"`
	Name            string      `json:"name"`
	Email           string      `json:"email"`
	Password        string      `json:"password"`
	EmailVerifiedAt interface{} `json:"email_verified_at"`
	CreatedAt       interface{} `json:"created_at"`
}
